#!/usr/bin/env python3
import sys
import json
from pathlib import Path
from typing import List, Dict, Any


def load_registry(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Registry index not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def build_rows(index: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = []
    runs = index.get("runs", {})
    for tid, t in index.get("theories", {}).items():
        name = t.get("theory_name", tid)
        source_type = t.get("source_type", "evolved")
        score = t.get("composite_score", 0.0)
        success_rate = t.get("success_rate", 0.0)
        run_id = t.get("run_id", "")
        model_src = t.get("generation_model_source", "")
        model_name = t.get("generation_model_name", "")
        row = {
            "theory_name": name,
            "source_type": source_type,
            "score": float(score) if isinstance(score, (int, float)) else 0.0,
            "success_rate": float(success_rate) if isinstance(success_rate, (int, float)) else 0.0,
            "run_id": run_id,
            "model_src": model_src,
            "model_name": model_name,
        }

        # Try to infer model for evolved theories if missing
        if source_type == "evolved" and (not row["model_src"] and not row["model_name"]):
            try:
                run_info = runs.get(run_id, {})
                run_path = run_info.get("run_path")
                if run_path:
                    import json, os
                    from pathlib import Path
                    manifest_file = Path(run_path) / "run_manifest.json"
                    if manifest_file.exists():
                        mf = json.loads(manifest_file.read_text(encoding="utf-8"))
                        cfg = mf.get("config", {})
                        row["model_src"] = cfg.get("synthesis_model_source") or row["model_src"]
                        row["model_name"] = cfg.get("synthesis_model_name") or row["model_name"]
                        if not (row["model_src"] and row["model_name"]):
                            # parse from eval_summary_path
                            target_name = name
                            for _tid, _tinfo in mf.get("theories", {}).items():
                                if _tinfo.get("theory_name") == target_name:
                                    p = Path(_tinfo.get("eval_summary_path", ""))
                                    # find ancestor 'run_*'
                                    run_folder = None
                                    for parent in [p] + list(p.parents):
                                        if parent.name.startswith("run_"):
                                            run_folder = parent.name
                                            break
                                    if run_folder:
                                        parts = run_folder.split("_")
                                        if len(parts) >= 4:
                                            row["model_name"] = row["model_name"] or "_".join(parts[3:])
                                        elif len(parts) >= 3:
                                            row["model_name"] = row["model_name"] or parts[2]
                                        mn = (row["model_name"] or "").lower()
                                        if "gemini" in mn:
                                            row["model_src"] = row["model_src"] or "google"
                                        elif "gpt" in mn or "o1" in mn or "openai" in mn:
                                            row["model_src"] = row["model_src"] or "openai"
                                        elif "deepseek" in mn:
                                            row["model_src"] = row["model_src"] or "deepseek"
                                        elif "grok" in mn or "xai" in mn:
                                            row["model_src"] = row["model_src"] or "xai"
                                    break
            except Exception:
                pass

        rows.append(row)
    # sort by score desc
    rows.sort(key=lambda r: r["score"], reverse=True)
    return rows


def sanitize(text: str, max_len: int = 64) -> str:
    if not isinstance(text, str):
        text = str(text)
    s = text.replace('_', '\\_')
    if len(s) > max_len:
        s = s[: max_len - 3] + '...'
    return s


def render_latex_table(rows: List[Dict[str, Any]], top_n: int = 15) -> str:
    header = [
        "% Auto-generated by scripts/gen_registry_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\caption{Global ranking with generation model (auto-generated).}",
        "\\label{tab:global-ranking-models}",
        "\\begin{tabular}{r l c c l}",
        "\\toprule",
        "Rank & Theory & Source & Score & Model \\",
        "\\midrule",
    ]

    lines = []
    if not rows:
        lines.append("\\multicolumn{5}{c}{No entries in registry} \\")
    else:
        for i, r in enumerate(rows[:top_n], 1):
            model = ""
            if r["model_src"] or r["model_name"]:
                model = f"{r['model_src']}/{r['model_name']}"
            line = (
                f"{i} & {sanitize(r['theory_name'])} & {sanitize(r['source_type'])} & "
                f"{r['score']:.3f} & {sanitize(model, max_len=48)} " + "\\\\")
            lines.append(line)

    footer = [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(header + lines + footer) + "\n"


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_registry_tables.py OUT_DIR", file=sys.stderr)
        sys.exit(1)
    out_dir = Path(sys.argv[1])
    out_dir.mkdir(parents=True, exist_ok=True)

    index_path = Path("global_theory_registry/theory_index.json")
    index = load_registry(index_path)
    rows = build_rows(index)

    # Write LaTeX table
    tex = render_latex_table(rows, top_n=20)
    (out_dir / "global_ranking_with_models.tex").write_text(tex, encoding="utf-8")

    # Also write a simple CSV without pandas
    csv_path = out_dir / "global_ranking_with_models.csv"
    with csv_path.open("w", encoding="utf-8") as f:
        f.write("rank,theory_name,source_type,score,success_rate,run_id,model_src,model_name\n")
        for i, r in enumerate(rows, 1):
            def esc(s):
                s = str(s).replace('"', "'")
                return s
            f.write(
                f"{i},\"{esc(r['theory_name'])}\",{r['source_type']},{r['score']:.3f},{r['success_rate']:.3f},{r['run_id']},{r['model_src']},{r['model_name']}\n"
            )

    print(f"Wrote {(out_dir / 'global_ranking_with_models.tex')} and CSV")


if __name__ == "__main__":
    main()
