#!/usr/bin/env python3
import sys
import json
import re
from pathlib import Path
from typing import List, Dict, Any


def find_run_manifests(root: Path) -> List[Path]:
    # Search for run_manifest.json under various output directories
    candidates = []
    for pattern in [
        "output_*/*/run_manifest.json",
        "output_*/*/*/run_manifest.json",
        "**/run_*/*/run_manifest.json",
    ]:
        candidates.extend(root.glob(pattern))
    # Deduplicate while preserving order
    seen = set()
    unique = []
    for p in candidates:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            unique.append(p)
    return unique

def find_eval_summaries(root: Path) -> List[Path]:
    patterns = [
        "output_*/*/final_evaluation_summary.json",
        "output_*/*/*/final_evaluation_summary.json",
        "**/run_*/final_evaluation_summary.json",
    ]
    out = []
    for pat in patterns:
        out.extend(root.glob(pat))
    # dedupe
    seen = set()
    uniq = []
    for p in out:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            uniq.append(p)
    return uniq


def extract_score(manifest: Dict[str, Any]) -> float:
    # Heuristics: try top-level 'score' or nested 'combined_score'
    score = None
    try:
        # Some manifests store under a list/dict; keep flexible
        if isinstance(manifest, dict):
            if "score" in manifest and isinstance(manifest["score"], (int, float)):
                score = float(manifest["score"])
            elif "combined_score" in manifest and isinstance(manifest["combined_score"], (int, float)):
                score = float(manifest["combined_score"])
            else:
                # Search shallow keys for combined score
                for k, v in manifest.items():
                    if isinstance(v, dict) and "combined_score" in v:
                        try:
                            score = float(v["combined_score"])
                            break
                        except Exception:
                            pass
    except Exception:
        pass
    return score if score is not None else float("nan")


def sanitize_run_id(p: Path) -> str:
    # Use the last two components as a readable run id
    parts = p.parts
    if len(parts) >= 2:
        return "/".join(parts[-3:]) if parts[-1] == "run_manifest.json" else "/".join(parts[-2:])
    return str(p)


def load_manifests(paths: List[Path]) -> List[Dict[str, Any]]:
    rows = []
    for path in paths:
        try:
            obj = json.loads(Path(path).read_text(encoding="utf-8"))
        except Exception:
            continue
        score = extract_score(obj)
        run_id = sanitize_run_id(path)
        rows.append({
            "run_id": run_id,
            "score": score,
            "path": str(path),
        })
    return rows

def load_eval_summaries(paths: List[Path]) -> List[Dict[str, Any]]:
    rows = []
    for path in paths:
        try:
            data = json.loads(Path(path).read_text(encoding="utf-8"))
        except Exception:
            continue
        # Expect a list of theories with success_rate; take best as score proxy
        best = 0.0
        if isinstance(data, list):
            for item in data:
                sr = item.get("success_rate")
                try:
                    if isinstance(sr, (int, float)):
                        best = max(best, float(sr))
                except Exception:
                    pass
        run_id = "/".join(path.parts[-3:])
        rows.append({
            "run_id": run_id,
            "score": best,
            "path": str(path),
        })
    return rows


def render_table(rows: List[Dict[str, Any]]) -> str:
    # Filter NaN and sort by score desc
    filtered = [r for r in rows if r["score"] == r["score"]]
    filtered.sort(key=lambda r: r["score"], reverse=True)
    top = filtered[:10] if filtered else []

    lines = []
    lines.append("% Auto-generated by scripts/gen_tables.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\caption{Top runs by composite score (auto-generated).}")
    lines.append("\\label{tab:auto-main-results}")
    lines.append("\\begin{tabular}{l c}")
    lines.append("\\toprule")
    lines.append("Run ID & Score " + "\\\\")
    lines.append("\\midrule")
    for r in top:
        lines.append(f"{r['run_id'].replace('_', '\\_')} & {r['score']:.3f} " + "\\\\")
    if not top:
        lines.append("\\multicolumn{2}{c}{No runs found} " + "\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_tables.py OUT_DIR", file=sys.stderr)
        sys.exit(1)
    out_dir = Path(sys.argv[1])
    out_dir.mkdir(parents=True, exist_ok=True)

    root = Path(__file__).resolve().parents[1]
    manifests = find_run_manifests(root)
    rows = load_manifests(manifests)
    # Also surface evaluation-only summaries to include recent offline runs
    eval_sums = find_eval_summaries(root)
    # Append a small sample so table stays compact but informative
    rows.extend(load_eval_summaries(eval_sums)[:3])
    content = render_table(rows)
    (out_dir / "main_results.tex").write_text(content, encoding="utf-8")
    print(f"Wrote {(out_dir / 'main_results.tex')}")


if __name__ == "__main__":
    main()
